# Generated by Django 4.1.4 on 2023-11-19 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_likes', models.IntegerField(default=0)),
                ('negative_likes', models.IntegerField(default=0)),
                ('car_model', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('languages', models.CharField(choices=[('EN', 'English'), ('UR', 'Urdu'), ('HI', 'Hindi'), ('OT', 'Others')], default='EN', max_length=2)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
